### 获取token
# @no-cookie-jar
POST http://localhost:8082/auth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### 验证token
GET http://localhost:8082/demo/getAuthentication
Content-Type: application/json
Authorization: Bearer eyJraWQiOiI5MDJiZWNlMS1jNjI5LTRiMDMtYWEyYy0zNzNhMzk0MWM3MDUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6Im1lc3NhZ2luZy1jbGllbnQiLCJuYmYiOjE3MTk5MDQwMjksInNjb3BlIjpbIm9wZW5pZCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODIiLCJleHAiOjE3MTk5MDQzMjksImlhdCI6MTcxOTkwNDAyOSwianRpIjoiYzAyMDVlMjktODVhOS00MDEwLTgwZTktYzJkNWY3NjRhMDUwIn0.YR7PlscWxgER-FTAdSsps6L26_VRzTZoIvmtyGqrNwedidkZtnrWfXNzoblFGrSDpUFXCAYLBQ2Obrak2WDOp5te6lvWWfXX1ULpxYE4ybuDRb0QLALX20QnGbHY-DAbumFDtvkU5vIKaP9HO-vD4qfaUEn_lgus7F4t76w57wqq2E_fgydETXp8r5EvTUocgMw6iCZxrJxJFyLwX0jHXn0iIB3Kt65sFGGabMJDhHoAtsOWbC-gm88waNXVNAI6Q4AKmu_oGx197CTprezvwtRIVEO1FheMTl3jYvMw_O0HmOL716n2aNqM0iPmdmSHvwd3ysgCk0nmHKUpz8LHsg

### 获取jwks
GET http://localhost:8082/oauth2/jwks
Content-Type: application/json

### 获取well-known
GET http://localhost:8080/gemini-uaa/.well-known/oauth-authorization-server
Content-Type: application/json

### swagger
GET http://localhost:8080/gemini-uaa/v3/api-docs
Content-Type: application/json

### 获取token
POST http://localhost:8082/oauth2/token
```