### 获取token
# @no-cookie-jar
POST http://localhost:8080/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic dXNlcjpwYXNzd29yZA==

### 验证token
POST http://localhost:8080/demo/hello
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJiM2E3ODhlMy02MWU5LTRlYjgtYjBkZi00NjU5OTJhNWU5MTYiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3VhYS5nZW1pbmkuZ2xzLmNvbSIsInN1YiI6InVzZXIiLCJleHAiOjE3MDg1OTc1NzUsImlhdCI6MTcwODU5Mzk3NSwic2NvcGUiOiJST0xFX1VTRVIifQ.k3OJI0ucGiiM8h0UecJZv5UvDsq0Fcu_0pvkyu2v48C4pt24nZPV6ydxNZvT1YVd2JXfM32SzyegW48rbVhy5sdCqt_CEAaMgqjIimEcDZooHSihwyaGXahVafmm0U-meHCVBQx_AgxJsy6EBWZN5QfegLjEKiQdk5tj8y2rqbm8H7jOGf7UPQjFgqtpd3omdzRFhON_-q-jyR5Yv-DITlgIfwtzpVAWWU0lfZsQLX3McfMhAQ2qxqKz4xVZUN6xWgrAyWAO9FI6fPpVUTdoJjAmm3bfdMLMcfdjqhVkeIBUP94nUHX11FudVSYCmyl1CGtgfghp9kogDtJT6U9jbg
